version: "2"
services:
  taar_amodump:
    environment:
      - PYTHONPATH=/app

      # Pickup the AWS secret and access key from host env
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_DEFAULT_REGION
      - MOZETL_COMMAND
      - MOZETL_GIT_PATH
      - MOZETL_GIT_BRANCH
      - MOZETL_SPARK_MASTER
      - MOZETL_SUBMISSION_METHOD
    build: .
    volumes:
      - .:/app
    command:
      "amodump"
